In [48]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [49]:
df = pd.read_csv("house.csv")

In [50]:
df

    size (sqft)  bedrooms   price
0          1000         2  200000
1          1500         3  300000
2          2000         4  400000
3          1200         2  220000
4          1800         3  350000
5          1000         2  200000
6          1500         3  300000
7          2000         4  400000
8          1200         2  220000
9          1800         3  350000
10         1000         2  200000
11         1500         3  300000
12         2000         4  400000
13         1200         2  220000
14         1800         3  350000
15         1000         2  200000
16         1500         3  300000
17         2000         4  400000
18         1200         2  220000
19         1800         3  350000
20         1000         2  200000
21         1500         3  300000
22         2000         4  400000
23         1200         2  220000
24         1800         3  350000

In [51]:
df.columns

Index(['size (sqft)', 'bedrooms', 'price'], dtype='object')

In [52]:
X = df[['size (sqft)','bedrooms']]

In [53]:
X

    size (sqft)  bedrooms
0          1000         2
1          1500         3
2          2000         4
3          1200         2
4          1800         3
5          1000         2
6          1500         3
7          2000         4
8          1200         2
9          1800         3
10         1000         2
11         1500         3
12         2000         4
13         1200         2
14         1800         3
15         1000         2
16         1500         3
17         2000         4
18         1200         2
19         1800         3
20         1000         2
21         1500         3
22         2000         4
23         1200         2
24         1800         3

In [54]:
y = df['price']

In [55]:
y

0     200000
1     300000
2     400000
3     220000
4     350000
5     200000
6     300000
7     400000
8     220000
9     350000
10    200000
11    300000
12    400000
13    220000
14    350000
15    200000
16    300000
17    400000
18    220000
19    350000
20    200000
21    300000
22    400000
23    220000
24    350000
Name: price, dtype: int64

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [57]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [58]:
new_data = pd.DataFrame([[3000,8]],columns=['size (sqft)', 'bedrooms'])

In [59]:
prediction = model.predict(new_data)
print(prediction)

[664565.75682382]

In [60]:
new_data = pd.DataFrame([[1800,3]],columns=['size (sqft)', 'bedrooms'])
prediction = model.predict(new_data)
print(prediction)

[345434.24317618]

In [61]:
print("Weights (coefficients)", model.coef_)

Weights (coefficients) [  152.10918114 27320.09925558]

In [62]:
print("intercept", model.intercept_)

intercept -10322.58064516139

In [63]:
y_pred = model.predict(X_test)

In [64]:
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

In [65]:
print(comparison.head())

    Actual      Predicted
24  350000  345434.243176
13  220000  226848.635236
12  400000  403176.178660
6   300000  299801.488834
2   400000  403176.178660

In [66]:
score = model.score(X_test, y_test)
print(score)

0.9961952608818937

In [67]:
print(f"Rows for training: {len(X_train)}")

Rows for training: 20

In [68]:
print(f"Rows for testing: {len(X_test)}")

Rows for testing: 5